AWSTemplateFormatVersion: 2010-09-09
Description: create code pipeline

Parameters:
  PJPrefix:
    Type: String
    Default: "playground"

  ServiceName:
    Type: String
    MinLength: 3
    MaxLength: 10
    AllowedPattern: '[a-z][a-z0-9\-]*'
    Default: server

  BuildTargetBranch:
    Description: build target (trigger) branch name
    Type: String
    Default: master

  BuildSpecPath:
    Description: buildspec file path in repository
    Type: String
    Default: buildspec.yml

  GitHubOAuthToken:
    Description: github oauth token
    Type: String
    NoEcho: true

  GitHubRepoOwner:
    Description: github owner name
    Type: String
    Default: akihokurino

  GitHubRepoName:
    Description: github repository name
    Type: String
    Default: aws-playground

Resources:
  # ------------------------------------------------------------#
  #  S3 Bucket
  # ------------------------------------------------------------#
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${PJPrefix}-${ServiceName}-artifact
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

  # ------------------------------------------------------------#
  #  code pipeline
  # ------------------------------------------------------------#
  PipelineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${PJPrefix}-${ServiceName}-pipeline-execution-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
      Policies:
        - PolicyName: pipeline-execution
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - "iam:PassRole"
                Resource: "*"
                Effect: Allow
                Condition:
                  StringEqualsIfExists:
                    iam:PassedToService:
                      - "cloudformation.amazonaws.com"
                      - "ec2.amazonaws.com"
                      - "ecs-tasks.amazonaws.com"
              - Action:
                  - "ec2:*"
                  - "elasticloadbalancing:*"
                  - "autoscaling:*"
                  - "cloudwatch:*"
                  - "s3:*"
                  - "sns:*"
                  - "cloudformation:*"
                  - "rds:*"
                  - "sqs:*"
                  - "ecs:*"
                  - "lambda:*"
                  - "codebuild:*"
                  - "codedeploy:*"
                  - "ecr:*"
                Resource: "*"
                Effect: Allow

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Sub ${PJPrefix}-${ServiceName}-artifact
      Name: !Sub ${PJPrefix}-${ServiceName}-${BuildTargetBranch}
      RestartExecutionOnUpdate: false
      RoleArn: !GetAtt PipelineExecutionRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: Srouce
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              RunOrder: 1
              Configuration:
                Branch: !Ref BuildTargetBranch
                OAuthToken: !Ref GitHubOAuthToken
                Owner: !Ref GitHubRepoOwner
                Repo: !Ref GitHubRepoName
                PollForSourceChanges: "true"
              OutputArtifacts:
                - Name: SourceArtifact
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              RunOrder: 1
              Configuration:
                ProjectName: !Ref BuildProject
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: ECS
                Version: 1
              RunOrder: 1
              Configuration:
                ClusterName: !Sub ${PJPrefix}
                ServiceName: !Sub ${PJPrefix}-${ServiceName}
                FileName: imagedefinitions.json
              InputArtifacts:
                - Name: BuildArtifact

  # ------------------------------------------------------------#
  #  code build
  # ------------------------------------------------------------#
  BuildExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${PJPrefix}-${ServiceName}-build-execution-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
      Policies:
        - PolicyName: build-execution
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${PJPrefix}-${ServiceName}
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${PJPrefix}-${ServiceName}:*
                Effect: Allow
              - Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:GetBucketAcl"
                  - "s3:GetBucketLocation"
                Resource:
                  - !Sub arn:aws:s3:::${PJPrefix}-${ServiceName}-artifact*
                Effect: Allow

  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Cache:
        Modes:
          - LOCAL_SOURCE_CACHE
          - LOCAL_DOCKER_LAYER_CACHE
        Type: LOCAL
      Environment:
        Type: LINUX_CONTAINER
        Image: aws/codebuild/standard:2.0
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
        PrivilegedMode: true
      Name: !Sub ${PJPrefix}-${ServiceName}
      ServiceRole: !GetAtt BuildExecutionRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref BuildSpecPath

Outputs: {}
