AWSTemplateFormatVersion: 2010-09-09
Description: ecs cluster

Parameters:
  ProjectName:
    Type: String
    Default: env-echo

Resources:
  # ------------------------------------------------------------#
  #  ECS Cluster
  # ------------------------------------------------------------#
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${ProjectName}

Outputs: {}
